export * from "./bootstrap-module.function";
export * from "./dgp-xp-module.function";
export { errorHandler } from "./error-handler";
export { removeRouteHandler } from "./remove-route-handler.function";
export { setRootInjector, getRootInjector } from "./root-injector.functions";
export { registerDecoratorMetadata } from "./register-decorator-metadata.function";
export { getDecoratorMetadata } from "./get-decorator-metadata.function";
export { registerDgpXpModuleMetadata } from "./register-dgp-xp-module-metadata.function";
export { getDgpXpModuleMetadata } from "./get-dgp-xp-module-metadata.function";
export { getNestedDgpXpModuleMetadata } from "./get-nested-dgp-xp-module-metadata.function";